import fs from 'fs'; import PizZip from 'pizzip'; import Docxtemplater from 'docxtemplater'
const zip=new PizZip(fs.readFileSync('src/assets/template-merps.docx'))
const doc=new Docxtemplater(zip,{paragraphLoop:true,linebreaks:true})
const rkpbm=Array.from({length:16},(_,i)=>{const ke=i+1,u=ke===8||ke===16;return{minggu:['I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI'][i],ujian:u,label:ke===8?'UJIAN TENGAH SEMESTER (UTS)':ke===16?'UJIAN AKHIR SEMESTER (UAS)':'',tujuan:'T'+ke,pokok:'P'+ke,metoda:'M',evaluasi:'4x50',buku:'B'+ke}})
doc.render({mata_kuliah:'Perpindahan Kalor',mata_kuliah_upper:'PERPINDAHAN KALOR',kode_mk:'KBPP 2152',sks:'2',jam_per_minggu:'4',semester_kelas:'VI',prasyarat:'Termo',perkiraan_peserta:'30',deskripsi_singkat:'Desk',tujuan_umum:'TU',tujuan_khusus:[{teks:'TK1'}],perkuliahan_jam:'36',perkuliahan_minggu:'9',latihan_jam:'8',latihan_minggu:'2',praktikum_jam:'12',praktikum_minggu:'3',ujian_jam:'4',total_jam:'60',buku_utama:[{teks:'BU'}],buku_pendukung:[{teks:'BP'}],uts:'30',uas:'40',nkp:'20',nkpr:'10',hbh_sikap:'10',hbh_latihan_kuis:'5',hbh_tugas:'5',etika_kerapian:'2,5',etika_kerja_sama:'2,5',etika_kedisiplinan:'2,5',etika_ketelitian:'2,5',rkpbm,kota:'Bengkalis',tanggal:'17 Juli 2026',dosen_utama_nama:'Syahrizal',dosen_utama_nomor:'NIP. 197310142021211005',ka_prodi_nama:'Bambang',ka_prodi_nomor:'NIP. 197801302021211004',ketua_jurusan_nama:'Ibnu',ketua_jurusan_nomor:'NIP. 197108102021211001',prodi_upper:'SARJANA TERAPAN TEKNIK MESIN PRODUKSI DAN PERAWATAN',jurusan_upper:'TEKNIK MESIN',institusi_upper:'POLITEKNIK NEGERI BENGKALIS'})
const out=doc.getZip().generate({type:'nodebuffer'}); fs.writeFileSync('/tmp/rendered2.docx',out)
const x=new PizZip(out).file('word/document.xml').asText()
const leftover=[...new Set([...x.matchAll(/\{[#/^]?[a-z_]+\}/g)].map(m=>m[0]))]
console.log('LEFTOVER:',leftover.length?leftover:'NONE')
const t=x.replace(/<[^>]+>/g,'').replace(/&amp;/g,'&')
;['PROGRAM STUDISARJANA TERAPAN TEKNIK MESIN PRODUKSI DAN PERAWATAN','JURUSAN TEKNIK MESIN','POLITEKNIK NEGERI BENGKALIS','KA PRODI SARJANA TERAPAN','KETUA JURUSAN TEKNIK MESIN'].forEach(s=>console.log((t.includes(s)?'OK   ':'MISS ')+s))
